version: 0.6.{build}-alpha

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration:
  - Release

before_build:
  nuget restore

cache:
- packages -> **\packages.config

test_script:
  - xunit.console.clr4.exe ChessLogic.UnitTests\bin\release\Chess.UnitTests.dll /appveyor

after_test:
  - nuget pack ChessLogic\ChessLogic.nuspec -Version "%APPVEYOR_BUILD_VERSION%"

artifacts:
  - path: '*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: er/U2/CvQ1PB7fzqLd58D6wEGLFo7jaOu1Id6ruQ8OeMckIgwqSXBtIz0rbIs3pQ
  artifact: /.*\.nupkg/

